<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AurumCRM.Communication\AurumCRM.Communication.csproj" />
      <ProjectReference Include="..\AurumCRM.Domain\AurumCRM.Domain.csproj" />
      <ProjectReference Include="..\AurumCRM.Exception\AurumCRM.Exception.csproj" />
    </ItemGroup>

</Project>
